# Generated by Django 5.0.4 on 2024-04-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='image',
            new_name='food_image',
        ),
    ]
