# Generated by Django 5.0.4 on 2024-07-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedfood',
            name='price',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='stripe-card', max_length=100),
        ),
    ]
